---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Mesdames, Messieurs,

Le développement de l’énergie éolienne a connu dans notre pays un essor important depuis le début des années 2000. En effet, en 2000 la puissance installée d’éolien en France n’était que de 47 MW, contre plus de 15 000 MW en 2018, soit 5,1 % de la production électrique française cette année‑là.

Cet accroissement du recours à l’énergie éolienne dans notre pays est appelé à être amplifié. En effet, le projet de programmation pluriannuelle de l’énergie (PPE) ambitionne de porter à 15 % la production d’électricité française d’origine éolienne en 2028.

Le respect de cet objectif supposerait de porter le nombre d’éoliennes terrestres d’environ 8 000 en 2018 à un nombre compris entre 14 200 et 15 500 en 2028, ainsi qu’à accroître sensiblement le nombre de parcs éoliens en mer.

Si le développement de cette énergie nouvelle pouvait susciter à l’origine de l’enthousiasme, l’implantation des parcs éoliens provoque aujourd’hui des oppositions de plus en plus fortes de la part des citoyens. Aujourd’hui, ce sont ainsi 7 projets éoliens sur 10 qui font l’objet d’un recours devant les juridictions administratives selon les conclusions du groupe de travail sur l’éolien publiées le 18 janvier 2018.

En effet, au‑delà de la promesse de permettre à la France de lutter contre le réchauffement climatique en faisant diminuer nos émissions de gaz à effet de serre (promesse par ailleurs non‑tenue du fait de l’existence de notre parc nucléaire qui nous offre déjà une électricité décarbonée), nous découvrons depuis quelques années la face sombre des projets éoliens. Nuisances sonores, paysages dévisagés, effets stroboscopiques, voire démarchage agressif de la part de certains promoteurs : les raisons de déchanter quant à l’implantation de ces machines sont nombreuses.

Ce développement mobilise par ailleurs des ressources financières considérables. Ainsi, sur la base d’un rapport relatif au soutien à l’éolien en France remis, en mai 2009, par la commission de régulation de l’énergie à la Commission des finances de l’Assemblée nationale, le coût de ce soutien a pu être estimé entre 72,7 et 90 milliards d’euros.

Cette proposition de loi vise donc à faire cesser ce qui relève aujourd’hui d’un développement à marche forcée des parcs éoliens, imposé contre les citoyens, en raisonnant celui‑ci.

L’article premier prévoit un allongement de la distance d’éloignement des éoliennes par rapport aux habitations. En effet, les études sanitaires qui ont été menées concernant les possibles nuisances causées par l’installation d’éoliennes à proximité des habitations (vibrations, effets stroboscopiques) sont parfois contradictoires et peuvent ne pas correspondre avec le ressenti réel des riverains. Il convient donc, par précaution, d’étendre la distance d’éloignement des éoliennes par rapport aux habitations. Comme les effets ne sont pas les mêmes selon la taille de l’éolienne, il est proposé de proportionner la distance aux premières habitations en fonction de la taille de l’éolienne, comme le recommande l’Académie de médecine dans son rapport du 3 mai 2017. Il est ainsi proposé de fixer un seuil de 1 500 mètres d’éloignement pour toutes les éoliennes dont la taille, pales comprises, est égale ou supérieure à 180 mètres, ce qui correspond aux dernières générations d’éoliennes, et de conserver le seuil de 500 mètres pour les éoliennes inférieures à 180 mètres de hauteur. Cet article propose également de préciser que les règles d’éloignement des éoliennes par rapport aux radars militaires, météorologiques, et de navigation aérienne, doivent s’assurer qu’il n’y aura pas d’interférences entre les éoliennes et ces équipements. Ces règles doivent en effet être fixées par un décret en Conseil d’État, mais nous remarquons que les militaires ont déjà perdu des arbitrages sur l’exclusion d’implantation d’éoliennes sur des zones utilisées pour des survols militaires. Il convient donc de préciser que le décret qui doit fixer ces règles protège réellement nos installations de toute interférence qui pourrait être causée par des éoliennes.

L’implantation d’un parc éolien représente une atteinte majeure au paysage dans lequel il s’insère, et peut avoir un impact sur l’économie locale. Il n’est donc pas envisageable qu’il puisse être implanté sans l’accord explicite de l’ensemble des communes concernées. L’article 2 prévoit donc que l’autorisation environnementale permettant de construire et d’exploiter un parc éolien ne pourra pas être délivrée, si au moins une des communes qui sont consultées avant ou durant l’enquête publique émet un avis négatif.

L’article 3 demande un rapport au Gouvernement sur les moyens de renforcer le volet sanitaire des études d’impact prévues au II de l’article L. 122‑1 du code de l’environnement pour les parcs éoliens. En effet, si les études d’impact conduites actuellement prévoient bien un volet sanitaire, force est de constater que celui‑ci n’est pas satisfaisant compte tenu des nombreuses plaintes émanant de riverains une fois les éoliennes installées. Il convient donc de rechercher rapidement les moyens de renforcer ces études sanitaires. 

Source : https://www.assemblee-nationale.fr/dyn/15/textes/l15b2781_proposition-loi#