---
title: "Dispositions ue terrorisme en ligne"
author: "Quentin GOLLENTZ"
date: "26/11/2022"
output: html_document
---

# Resume de la loi

La loi adapte le droit français pour garantir la mise en oeuvre du règlement européen du 29 avril 2021 relatif à la lutte contre la diffusion de contenus à caractère terroriste en ligne(nouvelle fenêtre).
Ce règlement dit "TCO" pour "terrorist content online", applicable depuis le 7 juin 2022, permet :

- aux autorités de chacun des 27 États européens d'imposer aux hébergeurs installés dans cet État et proposant leurs services dans l'UE le retrait dans l'heure des contenus terroristes ou leur blocage dans toute l'UE (injonctions nationales) ;
- aux autorités nationales d'émettre des injonctions de retrait transfrontalières lorsque l'hébergeur est localisé dans un autre État européen (procédure transfrontalière) ;
- aux hébergeurs et aux internautes à l'origine du contenu de saisir le juge pour contester une injonction de retrait.

Le règlement prévoit, par ailleurs, que les hébergeurs qualifiés d'"exposés" par l'autorité nationale doivent prendre des mesures pour lutter contre l'utilisation abusive de leurs plateformes (par exemple mobiliser des algorithmes pour filtrer et intercepter les contenus terroristes).

L'agence Europol est chargée de coordonner les injonctions des pays membres.
Les autorités chargées des injonctions de retrait en France

La loi modifie la loi du 21 juin 2004 pour la confiance dans l'économie numérique (LCEN). Elle désigne les autorités compétentes en France :

- pour émettre les injonctions nationales de retrait ou de blocage dans le cadre du règlement : il s'agit de l'Office central de lutte contre la criminalité liée aux technologies de l'information et de la communication (OCLCTIC), qui dépend de la direction centrale de la police judiciaire ;
- pour recevoir transmission de toutes les injonctions et instruire les injonctions transfrontalières : il s'agit d'une personne qualifiée au sein de l’Autorité de régulation de la communication audiovisuelle et numérique (Arcom, Ex-CSA). Elle pourra examiner la conformité de ces injonctions transfrontalières au regard du règlement européen "TCO" et de la charte des droits fondamentaux de l'UE.

L'Arcom devra également superviser les hébergeurs web qui sont situés principalement en France ou y ont un représentant légal et les mesures de prévention à la charge des plateformes considérées comme exposées.

Le nombre des hébergeurs situés en France est en train d'être évalué par le gouvernement.
Les sanctions et les recours concernant les plateformes en ligne

La loi précise par ailleurs :

- les sanctions pénales encourues par les hébergeurs qui ne respecteraient pas l'obligation de retrait ou de blocage ou qui n'informeraient pas les autorités d'un contenu terroriste "présentant une menace imminente pour la vie" ou annonçant un projet d'attentat (un an de prison et 250 000 euros d’amende, et pour une personne morale amende pouvant atteindre en cas d'infractions persistantes jusqu'à 4% de son chiffre d’affaires mondial) ;
-  les sanctions administratives et financières que pourra prononcer l'Arcom (mise en demeure pour un hébergeur de se conformer aux obligations du règlement européen et, en cas de non-conformité, amende pouvant aller jusqu'à 4% de son chiffre d’affaires mondial).

Les hébergeurs ou les internautes à l'origine des contenus, qui contestent une injonction de retrait, pourront former un référé-suspension ou un référé-liberté et déposer un recours en annulation dans les 48 heures devant le tribunal administratif, qui aura 72 heures pour statuer. Un appel pourra être formé dans les 10 jours. La cour administrative d'appel aura alors un mois pour trancher.

Ils pourront également demander l'annulation des décisions de l'Arcom.

La personne qualifiée de l'Arcom pourra, de son côté, saisir le tribunal administratif d'une injonction nationale de retrait si elle l'estime non fondée.
Des garanties pour les plateformes en ligne

Le règlement européen et la loi prévoient plusieurs garanties pour les hébergeurs web : des contenus terroristes précisément définis et listés, un délai de préavis de 12 heures avant la première injonction, le décompte du délai d'une heure à compter de la réception de l'injonction (et non de la notification), la possibilité pour un hébergeur de ne pas répondre à l'injonction en cas de force majeure, d'impossibilité de fait, d'erreurs manifestes ou d'informations incomplètes, l'obligation pour les hébergeurs de conserver les contenus pour les remettre en ligne en cas d'annulation de l'injonction, une procédure accélérée devant le juge administratif.

# Lien de référence

<https://www.vie-publique.fr/loi/285972-loi-16-aout-2022-retrait-contenus-terroristes-sur-internet-dans-lheure>.
