---
title: "Loi finances rectificative 2022"
author: "Quentin GOLLENTZ"
date: "26/11/2022"
output: html_document
---

# Resume de la loi

    


Le projet de loi de finances rectificative (PLFR) table sur une prévision de croissance de 2,7% du produit intérieur brut (PIB) et sur une inflation de 5,3% en 2022. Il ouvre des crédits et en annule d'autres, afin de financer des dépenses urgentes en particulier face à la hausse des prix de l'énergie. En 2022, le déficit public s'établirait à 5%, contre 6,5% en 2021. Le déficit budgétaire serait de 171 milliards d'euros.

2,5 milliards d'euros face à la hausse des prix de l'énergie

Le texte prévoit 2,4 milliards d'euros pour le pouvoir d'achat, dans le prolongement des mesures votées cet été. Ces crédits doivent financer :
  
  le chèque énergie exceptionnel annoncé par la Première ministre le 14 septembre 2022(nouvelle fenêtre) (à hauteur de 1,5 milliard d’euros). Ce chèque doit bénéficier à 12 millions de foyers, sous conditions de ressources. Il sera versé au mois de décembre. Son montant sera de 200 euros pour les 20% des foyers les plus modestes, qui perçoivent déjà le chèque énergie, et de 100 euros pour les ménages dont le revenu fiscal de référence est compris entre 10 800 euros et 17 400 euros ;
la prolongation de la remise carburant de 30 centimes par litre jusqu’au 15 novembre 2022 (à hauteur de 440 millions d’euros). La ristourne est de 10 centimes depuis le 16 novembre et ce jusqu’au 31 décembre 2022. Elle devrait être remplacée en 2023 par une aide ciblée destinée aux travailleurs qui prennent leur voiture pour aller travailler ;
un soutien aux universités et aux centres régionaux des œuvres universitaires et scolaires (Crous) pour payer leurs factures d'électricité ;
    les achats de carburants des armées.

Par amendements, les parlementaires ont complété ces mesures en votant :

*une aide de 230 millions d'euros pour les ménages se chauffant au bois* 
la reconduction en 2023 de l'attribution MaPrimeRénov' sans conditions de ressources pour des travaux de rénovation globale ;
le doublement du seuil d’imputation du déficit foncier sur le revenu global pour des dépenses de rénovation énergétique ;
une aide de 40 millions d'euros en faveur des associations d'aide alimentaire en raison de la hausse des prix de l'alimentation et de l'énergie.

Les autres dépenses : guerre en Ukraine et apprentissage

Dans le contexte de la guerre en Ukraine, plus d'1 milliard d'euros sont prévus pour des opérations extérieures des armées et la contribution de la France au renforcement du flanc oriental de l’OTAN. Un fonds spécial de 200 millions d'euros doit financer l’équipement militaire de l’Ukraine.

En matière d'apprentissage, 2 milliards d'euros renforceront la dotation d’équilibre à France compétences afin de tenir l’objectif de 800 000 contrats signés cette année.

450 millions d'euros sont, en outre, destinés au versement d'aides aux agriculteurs. Ces derniers ont été affectés en 2022 par plusieurs crises (influenza aviaire, crise porcine, épisode de gel) et l'impact sur les prix de la crise en Ukraine.

Sur amendements des parlementaires, des crédits supplémentaires ont été ouverts :
  
- 8 millions d'euros pour revaloriser les personnels des centres municipaux de santé ;
- une aide à la presse de 5 millions d'euros dans un contexte de hausse des prix du papier ;
- 100 millions d'euros pour la réfection des ponts et des routes, notamment des petites communes ;
- 50 millions d'euros pour la rénovation des réseaux d'eau ;
- 20 millions d'euros pour des travaux d'insonorisation pour les riverains d'aéroport ;
un coup de pouce de 12,5 millions d’euros pour les Maisons France services.

Une baisse des prêts garantis et participations financières de l’État

Au titre des annulations de crédits, le texte acte une baisse de 2 milliards d’euros des provisions pour les prêts garantis par l’État (PGE). Le programme relatif aux dépenses accidentelles est réduit.

Les parlementaires ont également diminué de 2 milliards d'euros les crédits du compte d'affectation spéciale "participations financières de l'État".


# Lien de référence

<https://www.vie-publique.fr/loi/286978-projet-de-loi-de-finances-rectificative-2022-budget-rectificatif-plfr-2>.
