---
title: "Maintien dispositif veille securite sanitaire"
author: "Quentin GOLLENTZ"
date: "2022-11-19"
output: html_document
---

# Resume de la loi

    
Le texte initial, présenté par le gouvernement, a été largement remanié par les parlementaires. Il s'agit de la première loi de la XVIe législature.
Les régimes sanitaires d'exception abrogés
    
La loi abroge expressément, à partir du 1er août 2022, les dispositions du code de la santé publique relatives à l'état d'urgence sanitaire ainsi que le régime de gestion de la crise sanitaire instauré par la loi du 31 mai 2021. Les mesures qu'ils autorisaient (confinement, couvre-feu, passe sanitaire...) ne pourront plus êtres édictées, sans une nouvelle loi.
    
Le régime de l’état d’urgence sanitaire avait été créé au tout début de la pandémie par la loi du 23 mars 2020 et avait été plusieurs fois prolongé. Le régime post-crise sanitaire avait été également renouvelé.
    
Initialement, le gouvernement avait prévu une fin implicite de ces deux régimes, qui devaient cesser de s'appliquer le 31 juillet 2022 conformément à la loi du 10 novembre 2021. Un amendement des sénateurs a abrogé formellement ces dispositifs, qui ne pourront plus être réactivités tels quels en cas de résurgence d'une crise sanitaire.
    
La fin de ces deux régimes entraine la dissolution du conseil scientifique Covid-19, qui est remplacé par un comité de veille et d'anticipation des risques sanitaires. Ce comité, créé par décret du 30 juillet 2022(nouvelle fenêtre), aura des missions plus larges que le conseil. Il est notamment chargé d'assurer une veille scientifique sur les risques sanitaires liés aux agents infectieux atteignant l'homme et l'animal, aux polluants environnementaux et alimentaires et au changement climatique et d'émettre des avis sur la stratégie à adopter pour lutter contre ces menaces.
Un test négatif aux frontières possible jusqu'au 31 janvier 2023
    
À partir du 1er août 2022 et jusqu'au 31 janvier 2023, la loi permet d'imposer aux personnes de plus de 12 ans la présentation d'un test Covid négatif lorsqu'elles voyagent :
    
vers la France depuis l’étranger ou vers la métropole depuis les outre-mer "en cas d'apparition et de circulation d'un nouveau variant du Covid-19 susceptible de constituer une menace sanitaire grave". Ce certificat sanitaire de voyage pourra être imposé avant l'embarquement dans les avions. Il pourra aussi concerner les personnels des services de transport concernés ;
vers l’outre-mer depuis la métropole en cas de "risque de saturation" des hôpitaux. Les personnels de transports sont aussi visés.
    
Les exécutifs locaux et les parlementaires élus dans la collectivité d'outre-mer concernée devront être consultés.
    
Cette obligation pourra être mise en place par un décret du Premier ministre, après avis du nouveau comité de veille et d'anticipation des risques sanitaires, pour deux mois maximum. Au-delà de cette durée, la présentation d'un test Covid négatif ne pourra être autorisée que par la loi et donc par un vote du Parlement.
    
À l'origine, le projet de loi du gouvernement prévoyait un passe sanitaire aux frontières jusqu'au 31 mars 2023.
Les fichiers SI-DEP et Contact Covid maintenus
    
Les traitements informatiques SI-DEP et Contact Covid, autorisés par la loi du 11 mai 2020 et plusieurs fois prolongés, sont maintenus.
    
Le fichier SI-DEP qui centralise les résultats des examens de dépistage du Covid-19, permet leur transmission ainsi que les certificats de rétablissement, est prolongé jusqu’au 30 juin 2023.
    
Le fichier Contact Covid qui identifie, oriente et accompagne les malades et les cas contacts, est maintenu jusqu'au 31 janvier 2023.
La question de la réintégration des soignants non vaccinés
    
À la suite d'un amendement des parlementaires, le texte envisage la possibilité de réintégrer les personnels de santé suspendus car non-vaccinés, lorsque l'obligation vaccinale ne sera plus justifiée médicalement.
    
L'obligation vaccinale pourra être suspendue par décret pour une partie ou tous les personnels qui y sont soumis après avis favorable de la Haute Autorité de santé (HAS), qui pourra être saisie par le gouvernement, par le nouveau comité médical, par l'une des deux commissions des affaires sociales du Parlement. Si la HAS conclut que l'obligation vaccinale n'a plus lieu d'être, ces personnels seront réintégrés.
    
Dans un avis rendu le 21 juillet 2022, la HAS s'est récemment prononcée contre la levée de cette obligation pour les professionnels des secteurs sanitaire et médico-social(nouvelle fenêtre). Elle avait été saisie par le ministre de la santé le 18 juillet.


# Lien de référence

<https://www.vie-publique.fr/loi/285591-loi-sanitaire-du-30-juillet-2022-fin-des-regimes-dexception>.
